/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Golden
 */
public class Calculatrice extends javax.swing.JFrame {

    /**
     * Creates new form Calculatrice
     */
    
    private double premierOperande = 0;
    private double secondOperande = 0;
    private char operation = ' ';
    private boolean attendNouvelOperande = false;
    
    public Calculatrice() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Calculatrice");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        btnEgal = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnCarre = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnFois = new javax.swing.JButton();
        btnMoins = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtAffiche = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Calculatrice"); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 10, 300));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 10, 240));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 10, 300));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 10));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 10));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 340, 10));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 340, 10));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 340, 10));

        btnEgal.setBackground(new java.awt.Color(102, 255, 0));
        btnEgal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEgal.setForeground(new java.awt.Color(255, 255, 255));
        btnEgal.setText("=");
        btnEgal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgalActionPerformed(evt);
            }
        });
        jPanel2.add(btnEgal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 60, 40));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("0");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 40));

        btnCarre.setBackground(new java.awt.Color(96, 37, 218));
        btnCarre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCarre.setForeground(new java.awt.Color(255, 255, 255));
        btnCarre.setText("x²");
        btnCarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarreActionPerformed(evt);
            }
        });
        jPanel2.add(btnCarre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 60, 40));

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CE");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton9.setText("7");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, 40));

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton10.setText("4");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 40));

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setText("1");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 40));

        btnDel.setBackground(new java.awt.Color(255, 153, 0));
        btnDel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("DEL");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 40));

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton13.setText("8");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, 40));

        jButton14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton14.setText("5");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 60, 40));

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton15.setText("2");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, 40));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText(".");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 60, 40));

        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton16.setText("9");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 60, 40));

        jButton17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton17.setText("6");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 60, 40));

        jButton18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton18.setText("3");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 60, 40));

        btnDivision.setBackground(new java.awt.Color(96, 37, 218));
        btnDivision.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel2.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 60, 40));

        btnFois.setBackground(new java.awt.Color(96, 37, 218));
        btnFois.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFois.setForeground(new java.awt.Color(255, 255, 255));
        btnFois.setText("*");
        btnFois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoisActionPerformed(evt);
            }
        });
        jPanel2.add(btnFois, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 60, 40));

        btnMoins.setBackground(new java.awt.Color(96, 37, 218));
        btnMoins.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMoins.setForeground(new java.awt.Color(255, 255, 255));
        btnMoins.setText("-");
        btnMoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoinsActionPerformed(evt);
            }
        });
        jPanel2.add(btnMoins, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, 40));

        btnPlus.setBackground(new java.awt.Color(96, 37, 218));
        btnPlus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        jPanel2.add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 60, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 300));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAffiche.setEditable(false);
        txtAffiche.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAffiche.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(txtAffiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
      
    private void btnEgalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgalActionPerformed
        // TODO add your handling code here:
       secondOperande = Double.parseDouble(txtAffiche.getText());
        double resultat = calculer();
        txtAffiche.setText(String.valueOf(resultat));
        premierOperande = resultat;
        attendNouvelOperande = true;
    }//GEN-LAST:event_btnEgalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("0");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarreActionPerformed
        // TODO add your handling code here:
        // Obtenez le nombre actuellement affiché
        double nombre = Double.parseDouble(txtAffiche.getText());
        // Calculez le carré du nombre
        double resultat = nombre * nombre;
        // Affichez le résultat
        txtAffiche.setText(String.valueOf(resultat));
        // Mettez à jour le premier opérande pour les calculs futurs
        premierOperande = resultat;
        attendNouvelOperande = true;
    }//GEN-LAST:event_btnCarreActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtAffiche.setText("0");
        premierOperande = 0;
        secondOperande = 0;
        operation = ' ';
        attendNouvelOperande = false;
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("7");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("4");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("1");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        String texte = txtAffiche.getText();
        if (!texte.isEmpty() && texte.length() > 1) {
            txtAffiche.setText(texte.substring(0, texte.length() - 1));
        } else {
            txtAffiche.setText("0");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("8");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("5");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("2");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        if (attendNouvelOperande) {
            txtAffiche.setText(String.valueOf(premierOperande));
        } else {
            premierOperande = Double.parseDouble(txtAffiche.getText());
        }
        operation = '/';
        attendNouvelOperande = true;
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnFoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoisActionPerformed
        // TODO add your handling code here:
        if (attendNouvelOperande) {
            txtAffiche.setText(String.valueOf(premierOperande));
        } else {
            premierOperande = Double.parseDouble(txtAffiche.getText());
        }
        operation = '*';
        attendNouvelOperande = true;
    }//GEN-LAST:event_btnFoisActionPerformed

    private void btnMoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoinsActionPerformed
        // TODO add your handling code here:
        if (attendNouvelOperande) {
            txtAffiche.setText(String.valueOf(premierOperande));
        } else {
            premierOperande = Double.parseDouble(txtAffiche.getText());
        }
        operation = '-';
        attendNouvelOperande = true;

    }//GEN-LAST:event_btnMoinsActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
       if (attendNouvelOperande) {
            txtAffiche.setText(String.valueOf(premierOperande));
        } else {
            premierOperande = Double.parseDouble(txtAffiche.getText());
        }
        operation = '+';
        attendNouvelOperande = true;
    }//GEN-LAST:event_btnPlusActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("9");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("6");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre("3");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ajouterChiffre(".");
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void calculerIntermediaire(java.awt.event.ActionEvent evt) {
        if (!txtAffiche.getText().isEmpty()) {
            String[] parties = txtAffiche.getText().split(" ");
            secondOperande = Double.parseDouble(parties[2].trim());
            premierOperande = calculer();
            txtAffiche.setText(String.valueOf(premierOperande));
        }
    }
    
    private double calculer() {
        switch (operation) {
            case '+':
                return premierOperande + secondOperande;
            case '-':
                return premierOperande - secondOperande;
            case '*':
                return premierOperande * secondOperande;
            case '/':
                if (secondOperande != 0) {
                    return premierOperande / secondOperande;
                } else {
                    txtAffiche.setText("Erreur");
                    return 0;
                }
            default:
                return secondOperande;
        }
    }
    
    private void ajouterChiffre(String chiffre) {
        if (attendNouvelOperande || txtAffiche.getText().equals("0")) {
            txtAffiche.setText(chiffre);
            attendNouvelOperande = false;
        } else {
            txtAffiche.setText(txtAffiche.getText() + chiffre);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarre;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEgal;
    private javax.swing.JButton btnFois;
    private javax.swing.JButton btnMoins;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtAffiche;
    // End of variables declaration//GEN-END:variables
}
